### ISSUE TITLE
How does  the Eraser work?

### ISSUE THREAD

**Issue by mePy2** [onyx-intl/OnyxAndroidDemo#9]

**Comment by wangsuicheng** [comment]
refer to ScribbleMoveEraserDemoActivity , use cap of a pen

**Comment by mePy2** [comment]
Hi,

I asked you because I noticed the behaviour of the Eraser is different from the pen.

The pen immediately pass the input from the Wacom layer to the E-Ink. And then, when a “refresh” is made, it gives the “path” to Android.

Instead the Eraser suddenly updates the application.

(This is related to the highlighter issue I opened too, since I want my highlighter mark to be suddenly “put” on the document, so a behaviour similar to the one of the Eraser in the Demo.)

**Comment by wangsuicheng** [comment]
> The pen immediately pass the input from the Wacom layer to the E-Ink. And then, when a “refresh” is made, it gives the “path” to Android.

Yes, because pen is drawing in framework then report touchList to app layer, when refresh, framework will clear handwriting track, and then app must draw the givin "path" 

> Instead the Eraser suddenly updates the application.

Because Eraser just report the input touchPointList to app, without drawing anything in framework,
let the app do erase

So based on the above, highlighter pen, this effect is not achieved in boox framework,  so you can use eraser to do with config your paint:

```
            paint.maskFilter = null
            paint.color = RED
            if (mode == MODE.ERASER) {
                paint.xfermode = PorterDuffXfermode(PorterDuff.Mode.CLEAR) 
            } else {
                paint.xfermode = null  
            }
            if (mode == MODE.HIGHLIGHTER) {
                paint.alpha = 100
            }
```

**Comment by mePy2** [comment]
Thank you,

I’ll give it a look asap.
